#name: Deploy meme ms from memelandia
#
#on:
#  push:
#    branches: [main]
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: SetUp Java
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'zulu'
#          java-version: '17'
#
#      - name: Build Project
#        run: mvn clean install -DskipTests
#
#      - name: Login Docker Hub
#        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
#
#      - name: Build Docker image
#        run: docker build -t  ${{secrets.DOCKER_USERNAME}}/meme-ms-memelandia .
#
#      - name: Push image to docker hub
#        run: docker push ${{secrets.DOCKER_USERNAME}}/meme-ms-memelandia
#
#  deploy:
#    needs: build
#    runs-on: self-hosted
#    steps:
#      - name: Pull image from docker hub
#        run: docker pull ${{secrets.DOCKER_USERNAME}}/meme-ms-memelandia:latest
#
#      - name: Remove container if exists
#        run: docker rm -f meme-ms-memelandia-container
#
#      - name: Run docker container
#        run: docker run -d -p 8083:8083 --name meme-ms-memelandia-container ${{secrets.DOCKER_USERNAME}}/meme-ms-memelandia:latest